#!/bin/sh -l

#SBATCH --nodes=1                     ##number of requested nodes (a node is a group of CPUs)
#SBATCH -n 99		              ##number of requested CPUs
#SBATCH --time=09:00:00               ##time requested
#SBATCH --job-name Final_Project      ##name of job
#SBATCH -A microbiome                 ##name of the queue you are using. Could be scholar or microbiome if you are on snyder

#########################################################################

echo "Start time"
date +"%d %B %Y %H:%M:%S"

#step 1, cd into the proper directory. This directory must already exist

cd $RCAC_SCRATCH
cd /scratch/bell/noomir/Noomir_finalproject_scratch/

pwd

#step 2, Load Modules

echo "loading bioinfo"
module load bioinfo

echo "loading qiime2-2023.9"
module load Qiime/2-2023.9

#step 3, 
qiime dada2 denoise-paired \
--i-demultiplexed-seqs demux_seqs.qza \
--p-trim-left-f 0 \
--p-trim-left-r 48 \
--p-trunc-len-f 0 \
--p-trunc-len-r 208 \
--o-representative-sequences rep-seqs.qza \
--o-table table.qza \
--o-denoising-stats denoising-stats.qza


echo "End time"
date +"%d %B %Y %H:%M:%S"

